import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/home.module.scss";
import { Header } from "./components/header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header lienRandom="/random" />
    </div>
  );
}
